// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"
#include "ui_Settings.h"

// Forward declare needle update helper (defined in main.cpp)
void update_needles_for_screen(int screen_num);

///////////////////// VARIABLES ////////////////////

// EVENTS
lv_obj_t *ui____initial_actions0;

// Screen tracking
static int ui_current_screen = 1;  // 1-5 for Screen1 through Screen5

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), true, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_Screen1_screen_init();
ui_Screen2_screen_init();
ui_Screen3_screen_init();
ui_Screen4_screen_init();
ui_Screen5_screen_init();
ui_Settings_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_Screen1);
}

void ui_destroy( void )
{ui_Screen1_screen_destroy();
ui_Screen2_screen_destroy();
ui_Screen3_screen_destroy();
ui_Screen4_screen_destroy();
ui_Screen5_screen_destroy();
}

// Get the current screen number (1-5)
int ui_get_current_screen(void)
{
    lv_obj_t* active = lv_scr_act();
    if (active == ui_Screen1) return 1;
    if (active == ui_Screen2) return 2;
    if (active == ui_Screen3) return 3;
    if (active == ui_Screen4) return 4;
    if (active == ui_Screen5) return 5;
    return 1; // Default to screen 1
}

// Navigate to next screen (swipe left)
void ui_next_screen(void)
{
    lv_obj_t* active = lv_scr_act();
    lv_obj_t* next = NULL;
    
    if (active == ui_Screen1) next = ui_Screen2;
    else if (active == ui_Screen2) next = ui_Screen3;
    else if (active == ui_Screen3) next = ui_Screen4;
    else if (active == ui_Screen4) next = ui_Screen5;
    else if (active == ui_Screen5) next = ui_Screen1;
    else next = ui_Screen1;
    
    if (next) {
        // Invalidate all cached images before switching screens to prevent stale images
        lv_img_cache_invalidate_src(NULL);
        // Force full re-render of the incoming screen: objects created on inactive
        // screens may have had their dirty flags consumed without actually being
        // rendered, so we must re-mark the whole screen dirty before the animation.
        lv_obj_invalidate(next);
        lv_scr_load_anim(next, LV_SCR_LOAD_ANIM_MOVE_LEFT, 300, 0, false);
        // Defer needle updates to the main loop (runs every 100ms)
        // Calling update_needles_for_screen() here raced with LVGL screen
        // load/animation and caused visual update issues. The periodic
        // updater will apply the values once the new screen is active.
    }
}

// Navigate to previous screen (swipe right)
void ui_prev_screen(void)
{
    lv_obj_t* active = lv_scr_act();
    lv_obj_t* prev = NULL;
    
    if (active == ui_Screen1) prev = ui_Screen5;
    else if (active == ui_Screen2) prev = ui_Screen1;
    else if (active == ui_Screen3) prev = ui_Screen2;
    else if (active == ui_Screen4) prev = ui_Screen3;
    else if (active == ui_Screen5) prev = ui_Screen4;
    else prev = ui_Screen1;
    
    if (prev) {
        // Invalidate all cached images before switching screens to prevent stale images
        lv_img_cache_invalidate_src(NULL);
        // Force full re-render of the incoming screen (same reason as ui_next_screen)
        lv_obj_invalidate(prev);
        lv_scr_load_anim(prev, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 300, 0, false);
        // Defer needle updates to the main loop (runs every 100ms)
        // Calling update_needles_for_screen() here raced with LVGL screen
        // load/animation and caused visual update issues. The periodic
        // updater will apply the values once the new screen is active.
    }
}

// Set the active screen directly (screen_num is 1-5)
void ui_set_screen(int screen_num)
{
    lv_obj_t* target = NULL;
    if (screen_num == 1) target = ui_Screen1;
    else if (screen_num == 2) target = ui_Screen2;
    else if (screen_num == 3) target = ui_Screen3;
    else if (screen_num == 4) target = ui_Screen4;
    else if (screen_num == 5) target = ui_Screen5;
    else target = ui_Screen1;

    if (target) {
        lv_img_cache_invalidate_src(NULL);
        lv_obj_invalidate(target);
        lv_scr_load_anim(target, LV_SCR_LOAD_ANIM_NONE, 200, 0, false);
    }
}
