// Icon path globals for C UI files
#ifdef __cplusplus
extern "C" {
#endif
extern char gauge_icon_paths[5][2][128]; // [screen][0=top,1=bottom][path]
#ifdef __cplusplus
}
#endif
// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

// Custom Inter font declarations
extern lv_font_t inter_16;
extern lv_font_t inter_24;
extern lv_font_t inter_48;
extern lv_font_t inter_72;
extern lv_font_t inter_96;
extern lv_font_t inter_120;
extern lv_font_t inter_144;

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////
#include "ui_Screen1.h"
#include "ui_Screen2.h"
#include "ui_Screen3.h"
#include "ui_Screen4.h"
#include "ui_Screen5.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// EMBEDDED BINARY IMAGES
LV_IMG_DECLARE(ui_img_upper_range_png);
LV_IMG_DECLARE(ui_img_lower_range_png);
LV_IMG_DECLARE(ui_img_lower_frame_backing_png);
LV_IMG_DECLARE(ui_img_lower_frame_cover_png);
LV_IMG_DECLARE(ui_img_default_png);

// IMAGES AND IMAGE SETS (SD CARD FILE PATHS)
extern const char *ui_img_rev_counter_png;   // assets/Rev_Counter.png (240x240)
extern const char *ui_img_temp_icon_png;   // assets/Temp_Icon.png
extern const char *ui_img_rev_fuel_png;   // assets/Rev_Fuel.png (240x240)
extern const char *ui_img_fuel_icon_png;   // assets/Fuel_Icon.png
extern const char *ui_img_temp_exhaust_png;   // assets/Temp_Exhaust.png (240x240)
extern const char *ui_img_exhaust_icon_png;   // assets/Exhaust_Icon.png
extern const char *ui_img_fuel_temp_png;   // assets/Fuel_Temp.png (240x240)
extern const char *ui_img_oil_temp_png;   // assets/Oil_Temp.png (240x240)
extern const char *ui_img_oil_icon_png;   // assets/Oil_Icon.png

// UI INIT
void ui_init(void);
void ui_destroy(void);
int ui_get_current_screen(void);
void ui_next_screen(void);
void ui_prev_screen(void);
// Set active screen directly (1-5)
void ui_set_screen(int screen_num);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
