// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"


// IMAGE DATA: assets/Temp_Icon.png
   const char *ui_img_temp_icon_png = "S:/assets/Temp_Icon.png";
