// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN3_H
#define UI_SCREEN3_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen3
extern void ui_Screen3_screen_init(void);
extern void ui_Screen3_screen_destroy(void);
extern lv_obj_t *ui_Screen3;
extern lv_obj_t *ui_TempExhaust;
extern lv_obj_t *ui_TopIcon3;
extern lv_obj_t *ui_BottomIcon3;
extern lv_obj_t *ui_Needle3;       // Temp needle
extern lv_obj_t *ui_Lower_Needle3;  // Exhaust Temp needle
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

