// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "screen_config_c_api.h"

lv_obj_t *ui_Screen4 = NULL;
lv_obj_t *ui_FuelTemp = NULL;
lv_obj_t *ui_TempIcon1 = NULL;
lv_obj_t *ui_BottomIcon4 = NULL;
lv_obj_t *ui_TopIcon4 = NULL;
lv_obj_t *ui_Needle4 = NULL;
lv_obj_t *ui_Lower_Needle4 = NULL;

// Swipe gesture tracking
static int16_t swipe_start_x = 0;
static int16_t swipe_start_y = 0;
static bool swipe_in_progress = false;

// event functions

// Swipe event handler for Screen4
static void screen4_swipe_event_cb(lv_event_t * e)
{
    lv_event_code_t code = lv_event_get_code(e);
    lv_obj_t * obj = lv_event_get_target(e);
    
    if (code == LV_EVENT_PRESSED) {
        lv_indev_t * indev = lv_indev_get_act();
        lv_point_t point;
        lv_indev_get_point(indev, &point);
        swipe_start_x = point.x;
        swipe_start_y = point.y;
        swipe_in_progress = true;
    }
    else if (code == LV_EVENT_RELEASED && swipe_in_progress) {
        lv_indev_t * indev = lv_indev_get_act();
        lv_point_t point;
        lv_indev_get_point(indev, &point);
        
        int16_t delta_x = point.x - swipe_start_x;
        int16_t delta_y = point.y - swipe_start_y;
        
        if (delta_x < -50 && abs(delta_x) > abs(delta_y)) {
            ui_next_screen();
        }
        else if (delta_x > 50 && abs(delta_x) > abs(delta_y)) {
            ui_prev_screen();
        }
        else if (delta_y > 50 && abs(delta_y) > abs(delta_x)) {
            extern lv_obj_t * ui_Settings;
            extern int previous_screen_before_settings;
            if (ui_Settings) {
                previous_screen_before_settings = 4;  // We're on Screen4
                lv_scr_load_anim(ui_Settings, LV_SCR_LOAD_ANIM_MOVE_BOTTOM, 300, 0, false);
            }
        }
        
        swipe_in_progress = false;
    }
}

// build funtions

void ui_Screen4_screen_init(void)
{
ui_Screen4 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

    ui_FuelTemp = lv_img_create(ui_Screen4);
    if (screen_configs[3].background_path[0] != '\0') lv_img_set_src(ui_FuelTemp, screen_configs[3].background_path);
    else lv_img_set_src(ui_FuelTemp, &ui_img_default_png); // Use embedded default background
lv_obj_set_width( ui_FuelTemp, LV_SIZE_CONTENT);  /// 669
lv_obj_set_height( ui_FuelTemp, LV_SIZE_CONTENT);   /// 669
lv_obj_set_align( ui_FuelTemp, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_FuelTemp, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_FuelTemp, LV_OBJ_FLAG_SCROLLABLE );    /// Flags


    // Top icon (dynamic)
    ui_TopIcon4 = lv_img_create(ui_Screen4);
    if (screen_configs[3].icon_paths[0][0] != '\0') {
        lv_img_set_src(ui_TopIcon4, screen_configs[3].icon_paths[0]);
        lv_obj_clear_flag(ui_TopIcon4, LV_OBJ_FLAG_HIDDEN);
    } else {
        lv_obj_add_flag(ui_TopIcon4, LV_OBJ_FLAG_HIDDEN);
    }
    _ui_apply_icon_style(ui_TopIcon4, 3, 0);
    lv_obj_set_width(ui_TopIcon4, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_TopIcon4, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_TopIcon4, 0);
    lv_obj_set_y(ui_TopIcon4, -70);
    lv_obj_set_align(ui_TopIcon4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TopIcon4, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(ui_TopIcon4, LV_OBJ_FLAG_SCROLLABLE);
    lv_img_set_zoom(ui_TopIcon4, 250);

    // Bottom icon (dynamic)
    ui_BottomIcon4 = lv_img_create(ui_Screen4);
    if (screen_configs[3].icon_paths[1][0] != '\0') {
        lv_img_set_src(ui_BottomIcon4, screen_configs[3].icon_paths[1]);
        lv_obj_clear_flag(ui_BottomIcon4, LV_OBJ_FLAG_HIDDEN);
    } else {
        lv_obj_add_flag(ui_BottomIcon4, LV_OBJ_FLAG_HIDDEN);
    }
    _ui_apply_icon_style(ui_BottomIcon4, 3, 1);
    lv_obj_set_width(ui_BottomIcon4, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_BottomIcon4, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_BottomIcon4, 0);
    lv_obj_set_y(ui_BottomIcon4, 70);
    lv_obj_set_align(ui_BottomIcon4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BottomIcon4, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(ui_BottomIcon4, LV_OBJ_FLAG_SCROLLABLE);
    lv_img_set_zoom(ui_BottomIcon4, 250);
    

// Top needle (Fuel) - green
ui_Needle4 = lv_line_create(ui_Screen4);
static lv_point_t needle4_points[] = {{240, 240}, {240, 240}};
lv_line_set_points(ui_Needle4, needle4_points, 2);
lv_obj_set_style_line_width(ui_Needle4, 10, 0); // width 10
lv_obj_set_style_line_color(ui_Needle4, lv_color_hex(0xFFFFFF), 0);
lv_obj_set_style_line_rounded(ui_Needle4, false, 0); // flat ends

// Bottom needle (Temp) - red
ui_Lower_Needle4 = lv_line_create(ui_Screen4);
static lv_point_t lower_needle4_points[] = {{240, 240}, {240, 240}};
lv_line_set_points(ui_Lower_Needle4, lower_needle4_points, 2);
lv_obj_set_style_line_width(ui_Lower_Needle4, 8, 0); // width 8
lv_obj_set_style_line_color(ui_Lower_Needle4, lv_color_hex(0xFF8800), 0);
lv_obj_set_style_line_rounded(ui_Lower_Needle4, false, 0); // flat ends

// Create transparent touch overlay for swipe detection
lv_obj_t * touch_overlay = lv_obj_create(ui_Screen4);
lv_obj_set_size(touch_overlay, 480, 480);
lv_obj_set_align(touch_overlay, LV_ALIGN_CENTER);
lv_obj_set_style_bg_opa(touch_overlay, 0, 0);
lv_obj_set_style_border_opa(touch_overlay, 0, 0);
lv_obj_clear_flag(touch_overlay, LV_OBJ_FLAG_SCROLLABLE);
lv_obj_add_event_cb(touch_overlay, screen4_swipe_event_cb, LV_EVENT_ALL, NULL);
}

void ui_Screen4_screen_destroy(void)
{
   if (ui_Screen4) lv_obj_del(ui_Screen4);

// NULL screen variables
ui_Screen4= NULL;
ui_FuelTemp= NULL;
ui_TopIcon4= NULL;
ui_TempIcon1= NULL;
ui_BottomIcon4= NULL;
ui_Needle4= NULL;
ui_Lower_Needle4= NULL;

}
