// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN4_H
#define UI_SCREEN4_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen4
extern void ui_Screen4_screen_init(void);
extern void ui_Screen4_screen_destroy(void);
extern lv_obj_t *ui_Screen4;
extern lv_obj_t *ui_FuelTemp;
extern lv_obj_t *ui_TopIcon4;
extern lv_obj_t *ui_TempIcon1;
extern lv_obj_t *ui_BottomIcon4;
extern lv_obj_t *ui_Needle4;       // Fuel needle
extern lv_obj_t *ui_Lower_Needle4;  // Temp needle
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

