// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN5_H
#define UI_SCREEN5_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen5
extern void ui_Screen5_screen_init(void);
extern void ui_Screen5_screen_destroy(void);
extern lv_obj_t *ui_Screen5;
extern lv_obj_t *ui_OilTemp;
extern lv_obj_t *ui_TopIcon5;
extern lv_obj_t *ui_TempIcon;
extern lv_obj_t *ui_BottomIcon5;
extern lv_obj_t *ui_Needle5;       // Oil Pressure needle
extern lv_obj_t *ui_Lower_Needle5;  // Temp needle
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

